package com.example.tabla_periodica;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.CardView;
import android.text.Editable;
import android.text.TextWatcher;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;
import java.util.ArrayList;
public class DescripcionDeDatos extends AppCompatActivity {


    String Descripcion[][] = {
            //todas las descripciones en lista
            {"El hidrógeno es el elemento químico más simple (formado solamente por un protón y un electrón) y más abundante del universo.",
                    "El helio es una sustancia de la naturaleza, concretamente un gas noble cuyo símbolo es He y que debe su nombre al Sol, que en griego se denomina helios.",
                    "Es un metal alcalino blanco plateado, blando, dúctil y muy ligero, se corroe rápidamente al contacto con el aire y no existe en estado libre en la naturaleza, sino solamente en compuestos; se utiliza en la fabricación de acero, en esmaltes y lubricantes, y el carbonato de litio, en medicina.",
                    "Es un metal de color gris, muy ligero, que se obtiene del berilo y se usa en la fabricación de aviones y tubos de rayos X, en los reactores nucleares y en computadoras, láser, televisión",
                    "El compuesto de boro de mayor importancia económica es el bórax que se emplea en grandes cantidades en la fabricación de fibra de vidrio aislante y perborato de sodio",
                    "Es un no metal sólido que es el componente fundamental de los compuestos orgánicos y tiene la propiedad de enlazarse con otros átomos de carbono y otras sustancias para formar un número casi infinito de compuestos",
                    "Es un gas incoloro, inodoro e inerte, compone cuatro quintos del volumen del aire de la atmósfera y se usa para sintetizar amoníaco y otros productos, para fabricar explosivos, como refrigerante y como atmósfera inerte para conservar ciertos productos.",
                    " es un gas incoloro e inodoro que se encuentra en el aire, en el agua, en los seres vivos y en la mayor parte de los compuestos orgánicos e inorgánicos; es esencial en la respiración y en la combustión",
                    "Es un gas a temperatura ambiente, de color verde pálido, formado por moléculas diatómicas F₂. Es el más electronegativo y reactivo de todos los elementos.",
                    "Es un gas noble, incoloro, prácticamente inerte, presente en trazas en el aire, pero muy abundante en el universo, que proporciona un tono rojizo (no es un color) característico a la luz de las lámparas fluorescentes en las que se emplea.",
                    " Es un metal alcalino blando, untuoso, de color plateado, muy abundante en la naturaleza, encontrándose en la sal marina y el mineral halita",
                    "es un metal alcalino de color blanco plateado, maleable y ligero, que existe en la naturaleza solamente en combinación química con otros elementos y es un componente esencial del tejido animal y vegetal; se usa en flashes fotográficos, señales luminosas, etc.",
                    "Se trata de un metal no ferromagnético. Es el tercer elemento más común encontrado en la corteza terrestre.",
                    "Es un no metal sólido, de color amarillento, que se extrae del cuarzo y otros minerales y es el segundo elemento más abundante en la Tierra después del oxígeno; se utiliza en la industria del acero como componente de las aleaciones de silicio y acero, en la fabricación de transistores y circuitos integrados",
                    "La principal función del fósforo es la formación de huesos y dientes. Este cumple un papel importante en la forma como el cuerpo usa los carbohidratos y las grasas. También es necesario para que el cuerpo produzca proteína para el crecimiento, conservación y reparación de células y tejidos",
                    "es un no metal de color amarillo pálido y olor desagradable, que se encuentra en la naturaleza tanto en forma libre como combinado con otros elementos; se usa para la obtención de ácido sulfúrico, para fabricar fósforos, caucho vulcanizado, tintes, pólvora, fungicidas, en fotografía para el fijado de negativos y positivos, y, en medicina para la elaboración de sulfamidas y pomadas tópicas.",
                    " El cloro existe como un gas amarillo-verdoso a temperaturas y presiones ordinarias. ... El cloro es uno de los cuatro elementos químicos estrechamente relacionados que han sido llamados halógenos.",
                    "El argón es el tercer miembro del grupo 0 en la tabla periódica. Los elementos gaseosos de este grupo se llaman gases nobles, inertes o raros, aunque en realidad el argón no es raro.",
                    "Ocupa un lugar intermedio dentro de la familia de los metales alcalinos después del sodio y antes del rubidio. Este metal reactivo es ligero y blando. ... El carbonato de potasio es también un material de partida importante en la industria del vidrio.",
                    " Los compuestos de calcio constituyen 3.64% de la corteza terrestre. ... Al igual que el berilio y el aluminio, pero a diferencia de los metales alcalinos, no causa quemaduras sobre la piel.",
                    "Es un metal de transición que se encuentra en minerales de Escandinavia y que se clasifica con frecuencia entre los lantánidos por sus similitudes con ellos.",
                    " Es un metal de transición de color gris, baja densidad y gran dureza. Es muy resistente a la corrosión por agua del mar, agua regia y cloro.",
                    " Es un metal dúctil, blando y poco abundante. Se encuentra en distintos minerales y se emplea principalmente en algunas aleaciones.",
                    " Es un metal que se emplea especialmente en metalurgia. Su nombre cromo se debe a los distintos colores que presentan sus compuestos.",
                    "Se encuentra como elemento libre en la naturaleza, a menudo en combinación con el hierro y en muchos minerales.",
                    "El hierro es el cuarto elemento más abundante en la corteza terrestre (5%). Es un metal maleable, tenaz, de color gres plateado y magnético",
                    "El cobalto aparece en la tabla periódica con el símbolo Co. Su número atómico es el 27 y fue reconocido como elemento básico entre 1730 y 1735, por el químico y minerólogo sueco Georg Brandt. Una cualidad de este mineral, es que es buen conductor del calor y la electricidad.",
                    "En forma comercial, el níquel se usa para forma aleaciones con el acero inoxidable y algunos otros metales que son resistentes a la corrosión.",
                    "uno de los metales de transición e importante metal no ferroso.",
                    "Es un metal maleable, dúctil y de color gris. Se conocen 15 isótopos, cinco de los cuales son estables y tienen masas atómicas de 64, 66, 67, 68 y 70.",
                    "Tiene un gran intervalo de temperatura en el estado líquido, y se ha recomendado su uso en termómetros de alta temperatura y manómetros. ... El galio es semejante químicamente al aluminio.",
                    "l mundo que rodea al ser humano se encuentra conformado por elementos tangibles e intangibles, es decir, por cosas que se pueden ver y viceversa. La matemática conforma a todo lo cuantificable, la física se encarga de todo lo que se toca y se mueve, mientras que la química se encuentra en la composición de absolutamente todo lo que es visible.",
                    "es un elemento químico de la tabla periódica cuyo símbolo es As y el número atómico es 33. En la tabla periódica de los elementos se encuentra en el quinto grupo principal",
                    "Selenio. El selenio es un elemento químico, cuyo símbolo es Se, con un número atómico de 34. ... El seleniuro de cadmio es un compuesto semiconductor que se usa en las fotoceldas pues su conductividad eléctrica cambia según la intensidad de la luz a la que se expone.",
                    "El bromo a temperatura ambiente es un líquido rojo, volátil y denso. Su reactividad es intermedia entre el cloro y el yodo",
                    " El kriptón es uno de los gases nobles. Es un gas incoloro, inodoro e insípido. Su principal aplicación es el llenado de lámparas eléctricas y aparatos electrónicos de varios tipos.",
                    "El rubidio es un elemento químico de la tabla periódica, su símbolo es el Rb y su número atómico es de 37. Es un metal con características altamente reactivas, su color es blanco plateado y es muy blando. Se encuentra en la naturaleza en estado extremadamente disperso. Usualmente se obtiene de la producción de litio. El rubidio se usa en células fotoeléctricas y para ciertos tipos de catalizadores",
                    "El estroncio es el menos abundante de los metales alcalinotérreos. La corteza de la Tierra contiene el 0.042% de estroncio, y este elemento es tan abundante como el cloro y el azufre.",
                    "Es un metal plateado de transición, común en los minerales de tierras raras.",
                    " El zirconio es uno de los elementos más abundantes y está ampliamente distribuido en la corteza terrestre. Es muy reactivo químicamente y sólo se halla combinado.",
                    "Es un metal de transición dúctil, gris, blando y poco abundante. Se encuentra en el mineral niobita, también llamado columbita, y se utiliza en aleaciones",
                    "El molibdeno es un metal esencial desde el punto de vista biológico y se utiliza sobre todo en aceros aleados.",
                    "El tecnecio es el más ligero de los elementos químicos que no cuentan con isótopos estables y el primer elemento sintético que se encuentra en la tabla periódica. Su número atómico es el 43 y su símbolo es Tc.",
                    "Es un metal de transición, poco abundante, del grupo del platino. Se encuentra normalmente en minas de platino y se emplea como catalizador en algunas aleaciones de platino",
                    " Es un metal de transición, poco abundante, del grupo del platino. Se encuentra normalmente en minas de platino y se emplea como catalizador en algunas aleaciones de platino.",

                    "Es un raro y brillante metal de color plateado, fue nombrado así por el asteroide Pallas.",
                    "Es un metal de transición suave, de color blanco y brillante, posee la mas alta conductividad eléctrica, térmica y reflectiva entre los metales.",
                    "Es un metal suave, de color blanco-azulado, químicamente es similar al Zinc y al Mercurio, tiene un  bajo punto de fusión a comparación con otros metales.",
                    "Es un metal de transición suave, maleable y con un bajo punto de fusión, el cual es más alto que el del Sodio pero más bajo que el del Litio o el Estaño.",
                    "Muestra un similitud química con el Germanio y el Plomo, forma parte de grupo principal en el grupo 14 de la tabla periódica.",
                    "Es un metaloide gris brillante, se encuentra principalmente en la naturaleza como el mineral sulfuro de estibina, sus compuestos se conocen desde la antiguedad y eran usados en cosméticos.",
                    "Es un metaloide de color blanco-plateado, frágil, levemente tóxico y raro, químicamente esta relacionado con el Selenio y el Azufre.",
                    "El yodo y sus compuestos se utilizan en nutrición, en la producción de ácido acético y ciertos polimeros, su nombre proviene del griego y significa violeta o purpura, debido al color del vapor del Yodo",
                    "Es un gas noble incoloro, denso e inodoro, se produce en la atmósfera de la tierra  en cantidades mínimas",
                    "Es un metal alcalino suave de color dorado-plateado, su punto de fusión es de 28c°, es uno de los 5 metales que se encuentran en estado líquido en o cerca de la temperatura ambiente.",
                    "Es un metal alcalinotérreo de color plateado métalico, debido a su alta reactividad química nunca se encuentra como un elemento libre en la naturaleza.",
                    "Es un metal  blando, dúctil, de color blanco-plateado, se lustra rapidamente cuando se expone al aire y es lo suficientemente suave para cortarlo con un cuchillo.",
                    "Es un metal blando, plateado y dúctil el cual se oxida fácilmente al exponerlo al aire.",
                    "Es un metal blando, plateado, dúctil y maleable, es valorado por sus propiedades magnéticas, eléctricas, químicas y ópticas.",
                    "Es un metal de color plateado, suave que se deslustra con el aire.",
                    "Químicamente es un lantanido que forma sales cuando se combina con otros elementos, todos sus isótopos son radioactivos.",
                    "Es un metal plateado moderadamente duro que se oxida fácilmente con el aire.",
                    "Es un metal moderadamente duro que se oxida fácilmente con el aire y el agua, lleva el nombre de el continente de Europa.",
                    "Es un metal de tierra rara, de color blanco-plateado, maleable y dúctil, en la naturaleza solo se encuentra de forma combinada.",
                    "Es un metal de tierra rara de color blanco-plateado,maleable, dúctil y lo suficientemente suave para cortarlo con un cuchillo, nunca se encuentra en la naturaleza como un elemento libre.",
                    "Es un elemento de tierra rara con un brillo metálico plateado, nunca se encuentra en la naturaleza como un elemento libre.",
                    "Elemento de tierra rara, forma parte de el grupo de los lantanidos",
                    "Metal solido de color blanco-plateado cuando se encuentra aislado artificialmente, es un elemento de tierra rara que se asocia con otros minerales de raros en el mineral gadolinita de Ytterby",
                    "Es el antepenultimo de la serie de los lantanidos y aligual que los otros lantanidos su estado de oxidación mas común es +3",
                    "Es el penúltimo de la serie de los lantánidos, al igual que los otros lantánidos su estado de oxidación mas común es +3, visto en su óxido, haluros y otros compuestos.",
                    "Es uno de los elementos del bloque d pero con freciencia se le suele incluir en los lantánidos debido a que comparte muchas propiedades con estos, de todos ellos es el mas difícil de aislar.",
                    "Es un metal de transición tetravalente, brillante, plateado y de color gris, se asemeja químicamente al Circonio y se encuentra en minerales de circonio.",
                    "Su nombre proviene de Tántalo, un antiheroe de la mitología griega, es un metal de transición lustroso, raro, duro, de color gris_azulado que es altamente resistente a la corrosión. ",
                    "Tambien conocido como tungsteno, palabra que proviene de la lengua sueca tung sten que significa piedra pesada.",
                    "Es un metal de transición de la tercera fila, grueso y de color plateado, es uno de los elementos más raros en la corteza terrestre.",
                    "Es un metal de transición de color blanco_azulado, duro y frágil en el grupo del platino que se encuentra como un elemento traza en las aleaciones. Es el elemento natural más denso.",
                    "Es unmetal de transición duro, frágil, de color platino-blanco, generalmente se le atribuye como el segundo elemento  más denso  basado en la densidad medida.",
                    "Es unmmetal de transición denso, maleable, dúctil, altamente no reactivo, precioso y de color gris-blanco, su nombre deriva del termino español platina, que se traduce como poca plata.  ",
                    "En su forma más pura, es un metal brillante, ligeramente rojizo, denso, suave, maleable y dúctil, químicamente es un metal de transición.",
                    "Es un elemento del bloque d pesado y de color plateado, es el único elemento metálico que es líquido en condiciones estándar de temperatura y presión.",
                    "Es un metal de transición suave y de color gris, no se encuentra libre en la naturaleza, cuando se encuentra aislado, se parece al estaño pero se decolora al exponerlo al aire.",
                    "Es u metal blando, maleable y pesado despues de la transición, al exponerlo al aire se torna de un color gris o opaco.",
                    "Es unmetal de transición posterior pentavalente, químicamente se asemeja al arsénico y el antimonio, los cristales de bismuto  suelen adoptar formas geométricas y poseen una amplia grama de colores.",
                    "Es un elemento raro y altamente radioactivo sin isótopos estables, es químicamente similar al bismuto y al telurio, sus aplicaciones son pocas.",
                    "Ocurre en la Tierra como el producto de desintegración de varios elementos más pesados. Todos sus isótopos son de corta duración.",
                    "Es un gas noble radioactivo, incoloro, inodoro e insípido, que se produce naturalmente como producto de la desintegración del radio.",
                    "Es el segundo elemento menos electronegativo, solo detras del cesio, es un metal altamente radioactivo que se descompone en astatino, radio y radón.",
                    "El radio puro es casi incoloro, pero se combina fácilmente con nitrógeno en la exposición al aire, formando una capa negra de nitruro de radio.",
                    "Fue el primer elemento radioactivo no primordial en aislarse, due descubierto en 1899.",
                    "Es uno de los 2 elementos significativamente radioactivos que aún ocurren naturalmente en grandes cantidades como elemento primordial, el otro es el Uranio.",
                    "Es un metal denso de color gris-plateado que reacciona fácilmente con el oxígeno, el vapor de agua y los ácidos inorgánicos.",

                    "El uranio tiene el mayor peso atómico de entre todos los elementos que se encuentran en la naturaleza.",
                    "Su nombre proviene del planeta Neptuno.",
                    "Es un metal radiactivo, de color plateado, muy tóxico debido a su alta radiactividad, que se encuentra en cantidades muy pequeñas en las menas de uranio",
                    "El amerecio es un catión poliatómico cargado positivamente",
                    "Se produce bombardeando plutonio con partículas alfa.El curio no existe en el ambiente terrestre, pero puede producirse en forma artificial.",
                    "Pertenece a la serie de los actínidos y elementos transuránicos",
                    "Este elemento fue obtenido por primera vez en la Universidad de California en Berkeley en 1950 bombardeando curio con partículas alfa",
                    "El elemento químico einstenio fue descubierto por Albert Ghiorso junto con un grupo de investigadores quienes trabajaban en la Universidad de California",
                    "El fermio es un elemento químico radiactivo creado artificialmente",
                    "El nombre de este elemento proviene del creador de la Tabla periódica de los Elementos: Dmitri Mendeleyev",
                    "Hasta la fecha sólo se han producido cantidades atómicas del elemento. El nobelio es el décimo elemento más pesado",
                    "El lawrencio, nombrado así en honor de E. O. Lawrence, es el undécimo elemento transuránico",
                    "Su nombre fue elegido en honor del Barón Ernest Rutherford, científico colaborador del modelo atómico y física nuclear.",
                    "El elemento fue nombrado en honor a la ciudad de Dubna, Rusia, donde fue producido por primera vez",
                    "Es un elemento sintético cuyo isótopo más estable y que tiene una vida media de 2,4 minutos. ",
                    "Su nombre le fue dado en honor al científico danés Niels Bohr. Elemento químico que se espera que tenga propiedades químicas semejantes a las del elemento renio.",
                    "El hasio, ​ anteriormente conocido provisionalmente como unniloctio, ​​, es un elemento sintético de la tabla periódica",
                    "El meitnerio (anteriormente llamado unnilenio con símbolo provisional Une o Wolschakio con símbolo Wl al no ser oficial)​​ es un elemento químico",
                    "El darmstatio​ (anteriormente llamado ununnilio con símbolo provisional Uun o madveded, madvedevio o medvedio​ con símbolo Mv al no ser oficial)​​ es un elemento químico.",
                    "También tenía asignado el nombre de plutirio con el símbolo Pl al no ser oficial​. Fue descubierto en 1994 por científicos alemanes en Darmstadt.",
                    "El ununbio (Uub) es un nombre temporal para referirse al elemento químico",
                    "El tusfrano es un elemento químico radiactivo",
                    " Elemento químico relativamente nuevo, cuyo descubrimiento se atribuye a los rusos. ",
                    "es un combustible magnifico ya que no es de este planeta, ya que fue encontrado en naves extraterrestre",
                    "El Nectarien es un elemento químico que no está aprobado oficialmente por la IUPAC y que no tiene una fecha determinada de su descubrimiento.",
                    "Este nuevo elemento químico fue creado al hacer colisionar isótopos de calcio",
                    "El oberón o ununoctio (conocido anteriormente como eka-radón); nombre sistemático temporal dado por la Unión Internacional de Química Pura y Aplicada al elemento sintético transactínido",
            }
    };
}